Promotec/WebDemo02/Controllers/ListarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace WebDemo02.Controllers
{
    public class ListarController : Controller
    {
        
        public ActionResult Index()
        {
            return View();
        }

             


        public JsonResult listarTodo()
        {
            promotecEntities3 a = new promotecEntities3();

            string dni = LoginController.DNI;

            IEnumerable<WebDemo02.Models.Eventos> search = a.Evento.Select(x => new WebDemo02.Models.Eventos
            {   fecha = x.fecha,
                hora = x.hora,
                nombre = x.nombre,
                lugar = x.lugar,
                dni = x.dni
            }).Where(y => y.dni == dni);
            
            return  Json(search, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult listarlistarporfecha(DateTime val1)
        {
            
            promotecEntities3 a = new promotecEntities3();
         
            IEnumerable<WebDemo02.Models.Eventos> newRequest = a.Evento.Select(x => new WebDemo02.Models.Eventos
            {
                fecha = x.fecha,
                hora = x.hora,
                nombre = x.nombre,
                lugar = x.lugar,
                dni = x.dni
            }).Where(y => y.fecha == val1);

            return Json(newRequest, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public JsonResult listarlistarporname(string val1)
        {

            promotecEntities3 a = new promotecEntities3();

            IEnumerable<WebDemo02.Models.Eventos> newRequest = a.Evento.Select(x => new WebDemo02.Models.Eventos
            {
                fecha = x.fecha,
                hora = x.hora,
                nombre = x.nombre,
                lugar = x.lugar,
                dni = x.dni
            }).Where(y => y.nombre == val1);

            return Json(newRequest, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public JsonResult listarlistarportime(string val1)
        {

            promotecEntities3 a = new promotecEntities3();

            IEnumerable<WebDemo02.Models.Eventos> newRequest = a.Evento.Select(x => new WebDemo02.Models.Eventos
            {
                fecha = x.fecha,
                hora = x.hora,
                nombre = x.nombre,
                lugar = x.lugar,
                dni = x.dni
            }).Where(y => y.hora == val1);

            return Json(newRequest, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public JsonResult listarlistarpor(DateTime val1, string val2, string val3)
        {

            promotecEntities3 a = new promotecEntities3();

            IEnumerable<WebDemo02.Models.Eventos> newRequest = a.Evento.Select(x => new WebDemo02.Models.Eventos
            {
                fecha = x.fecha,
                hora = x.hora,
                nombre = x.nombre,
                lugar = x.lugar,
                dni = x.dni
            }).Where(y => y.fecha == val1 && y.nombre == val2 && y.hora == val3);

            return Json(newRequest, JsonRequestBehavior.AllowGet);
        }

    }
}

Promotec/WebDemo02/Controllers/RegistrarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebDemo02.Controllers
{
    public class RegistrarController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }

        
        [HttpPost]
        public JsonResult PostMethod(WebDemo02.Models.Eventos evento)
        {
            string dni = LoginController.DNI;
            promotecEntities3 a = new promotecEntities3();
            WebDemo02.Models.Eventos person = new WebDemo02.Models.Eventos
            {
                nombre = evento.nombre,
                fecha = evento.fecha,
                lugar = evento.lugar,
                hora = evento.hora,
                dni = dni,
                Usuario = a.usuario.FirstOrDefault(x => x.dni == dni)
            };
            try
            {
                a.Evento.Add(person);

                a.SaveChanges();
                return Json("Registrado");
            }
            catch (Exception e)
            {
                return Json(e);
                throw;
            }


        }

    }
}

Promotec/WebDemo02/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />

    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-grid.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Content/font_/css/font-awesome.min.css">

    <script src="~/Scripts/modernizr-2.6.2.js"></script>

</head>
<body>
    <div class="navbar navbar-expand-sm navbar-light  fixed-top bg-white">
        <a href="#menu-toggle" id="menu-toggle" class="navbar-brand"><span class="navbar-toggler-icon"></span></a> <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample02" aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span> </button>
        <a class="navbar-brand" href="~/Home">            
            <img src="~/Content/pormotec_logo.png" width="30" height="30" class="d-inline-block align-top" alt="" />
            Promotec
        </a>
        <div class="container">
            <div class="navbar-header">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Lista de Eventos", "Index", "Listar", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Crear un Evento", "Index", "Registrar", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
               
                <ul class="nav navbar-nav mr-auto"></ul>
                <ul class="nav navbar-nav navbar-right ">
                    <li class="nav-item"><p class="d-inline-block align-top" style="margin-right: 30px ; margin-top: 10px"><em>Bienvenido: @WebDemo02.Controllers.LoginController.NOMBRE</em></p></li>
                    <li class="nav-item"><a href="/Login" id="loginLink" class="nav-link">Salir</a></li>
                </ul>
            </div>
        </div>
    </div>
    

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="footer navbar-fixed-bottom">


            <div class="container">
                <p class="m-0 text-center text-white">Copyright &copy; @DateTime.Now.Year</p>
            </div>

        </footer>
    </div>
    

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>